# More details: https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
project:
  type: website
  output-dir: docs

website:
  title: "Home"
  google-analytics: "UA-263609196-1"
  site-url: https://minsuk-sung.github.io
  repo-url: https://github.com/minsuk-sung/minsuk-sung.github.io
  body-footer: Copyright © 2023 Minsuk Sung All rights reserved.
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/minsuk-sung
      - icon: twitter
        href: https://twitter.com
format:
  html:
    toc: true
    theme: [cosmo, theme.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap



